### ISSUE TITLE
Set synthetic value directly inside configurations

### ISSUE THREAD

**Issue by igordeoliveirasa** [zazoomauro/node-dependency-injection#100]
Is there this feature?

**Comment by zazoomauro** [comment]
all the features are fully documented on the wiki page. Can you please give me a more specific example of what exactly you want to achieve?

**Comment by igordeoliveirasa** [comment]
Thanks for your answer.

I'd like to have a block that sets synthetic values directly, at the same configuration file.
I'm using JsFileLoader..

If I could do something like:

```
module.exports = {
    services: {
        "settings.mailer-connection": {
                 value: {
    host: process.env.MAILER_SMTP_DOMAIN,
    port: parseInt(process.env.MAILER_SMTP_PORT),
    secure: (process.env.MAILER_SMTP_SECURE || "FALSE").trim().toUpperCase() == 'TRUE', // use SSL
    auth: {
        user: process.env.MAILER_SMTP_AUTH_USER,
        pass: process.env.MAILER_SMTP_AUTH_PASSWORD,
    },
    from: process.env.MAILER_SMTP_FROM
}
        }
    }
};

```

Would be great!

**Comment by zazoomauro** [comment]
So, you would like to inject objects as parameters?

**Comment by igordeoliveirasa** [comment]
Yes, without having to set parameters at a .js, but at the same config.js.

**Comment by zazoomauro** [comment]
check this: https://github.com/zazoomauro/node-dependency-injection/wiki/Parameters

**Comment by igordeoliveirasa** [comment]
Now I got it. Thanks!
