### ISSUE TITLE
FileLoader extending a MemoryLoader

### ISSUE THREAD

**Issue by igordeoliveirasa** [zazoomauro/node-dependency-injection#102]
I'd like to create a MemoryLoader and make FileLoader to extend it. At MemoryLoader I'll be decoupling FileLoader to contain methods that treat what has already been read from FileLoader. It will give me a new loader (MemoryLoader) that will be able to read a possible dynamic generated di settings.

I'm almost forking and creating that feature. Would you agree my PR?

**Comment by igordeoliveirasa** [comment]
Honestly, I'd like to list all *.di.js of my project, each one follows JsFileLoader syntaxes, compose a list of them and build the container dynamically.

**Comment by zazoomauro** [comment]
Your MemoryLoader is a JsFileLoader but with some of your product logic inside. Am I wrong?
Can you please, explain me better, this: `will be able to read a possible dynamic generated di settings`.
Can you give some real example of usage?
Thanks

**Comment by igordeoliveirasa** [comment]
@zazoomauro I'd like to pass json to a loader instead of a file containing that json. That is it.

**Comment by igordeoliveirasa** [comment]
I guess I'm not able to make this change since I don't have time to learn and follow your development conventions/ways. But I just would like to pass json directly to a loader instead of reading it from a existing file.

**Comment by igordeoliveirasa** [comment]
Instead of having a file containing:

```
module.exports = {
    imports: [
		{resource: "../settings-a.config.js"},
		{resource: "../settings-b.config.js"},
                 ...
   ]
}
```

I'd like to have a loader able to receive:
```
{
    imports: [
		{resource: "../settings-a.config.js"},
		{resource: "../settings-b.config.js"},
                 ...
   ]
}
```

**Comment by zazoomauro** [comment]
what about the JsonLoader? is already there, up and running

**Comment by igordeoliveirasa** [comment]
@zazoomauro you gotta be kidding... lol... It's not on the  docs.. 😁

**Comment by igordeoliveirasa** [comment]
I'm suggesting a JsonLoader. (without file reading dependency)

**Comment by zazoomauro** [comment]
https://github.com/zazoomauro/node-dependency-injection/wiki/ConfigurationFiles

**Comment by igordeoliveirasa** [comment]
@zazoomauro I guess I'm not being able to make you understand me. Sorry. JsonFileLoader needs a filepath to work. Im suggesting a new loader (not FILE LOADER) that only needs a variable storing a json settings.

**Comment by zazoomauro** [comment]
ok... like this

instead of 
`new JsonFileLoader(..some/path)`

this

`new JsonLoader({my-config...});`

**Comment by igordeoliveirasa** [comment]
Yes it is!!!

**Comment by zazoomauro** [comment]
Could be a good idea and easy to implement

**Comment by igordeoliveirasa** [comment]
I'm going to try it.. Ok?

**Comment by zazoomauro** [comment]
Sure! Read this first https://github.com/zazoomauro/node-dependency-injection/blob/master/CONTRIBUTING.md

**Comment by igordeoliveirasa** [comment]
@zazoomauro 

I tried JsonLoader like, (before decoupling FileLoader..): 
```
import FileLoader from './FileLoader'

export default class JsonLoader extends FileLoader {
  /**
   * @param {object|null} content
   */
  load (content) {
    content = content || {}
    content.imports = content.imports || []
    content.parameters = content.parameters || []
    content.services = content.services || []

    this._parseImports(content.imports)
    this._parseParameters(content.parameters)
    this._parseDefinitions(content.services)
  }
}
```


However unfortunately I won't be able to contribute since all loaders depend on _requireClassNameFromPath method to read definitions. As you know the code as nobody I suppose you are the best guy to bring us this feature.

**Comment by zazoomauro** [comment]
I really don't think extending from FileLoader is a good idea... we are not using a file anymore. maybe we can create an InlineLoader and create a bunch of loaders extending this.

**Comment by mpontus** [comment]
Has this feature been realized? I think it could be very useful when using `webpack` or `esbuild` which would leave out files not referenced explicitly through `import` or `require`.
