### ISSUE TITLE
Why `path` ?

### ISSUE THREAD

**Issue by agung-wete** [zazoomauro/node-dependency-injection#108]
https://github.com/zazoomauro/node-dependency-injection/blob/f99038c75ff368dccb53e70c3a491b795d877891/package.json#L66

`path` is nodejs builtin module

**Comment by agung-wete** [comment]
also https://github.com/zazoomauro/node-dependency-injection-express-middleware/blob/67fb69355896b6d11650c6cb20ed224ce6cfdac1/package.json#L41

**Comment by zazoomauro** [comment]
@agung-wete totally right. My mistake!
