### ISSUE TITLE
A conflict with objectionjs package

### ISSUE THREAD

**Issue by vladimirice** [zazoomauro/node-dependency-injection#118]
Please observe a dependency conflict I've found recently. Maybe this issue will help to improve your project. Thanks!

https://github.com/Vincit/objection.js/issues/1350

**Comment by zazoomauro** [comment]
@vladimirice but can you please, explain me the issue here?

**Comment by vladimirice** [comment]
Please observe a test project to investigate it.

https://github.com/vladimirice/objection-postgresql

If I add node-dependency-injection (declaration only) then objectionjs relational feature stops to work and throw an error.
https://github.com/vladimirice/objection-postgresql/blob/master/example.js#L8

I don't know yet is it a problem in objectionjs or a problem in node-dependency-injection. The situation is:
* node-dependency-injection works with objectionjs
* objectionjs does not work properly if node-dependency-injection is used (declaration is enough)

node -v v10.15.2
npm -v 6.9.1-next.0
PostgreSQL 10.6

That's a pity I need objectionjs features a lot so I have to stop using your wonderful library :(

**Comment by zazoomauro** [comment]
I know where is the issue here

in your example instead of 
`const { ContainerBuilder } = require('node-dependency-injection');`
use 
`const map = require('collections/map');`

investigating why...

**Comment by zazoomauro** [comment]
Btw. I can try to avoid the collections lib usage

**Comment by zazoomauro** [comment]
Version 2.3.4 ready for you
