### ISSUE TITLE
File names in dist/bin folder are not zippable on windows

### ISSUE THREAD

**Issue by pinnprophead** [zazoomauro/node-dependency-injection#121]
Can the ndi-config<char>check.js, ndi-config<char>create.js and ndi-container<char>service.js files be renamed so that the filenames are acceptable to zip on windows?

Perhaps the character could be changed to a dash or a ~.

**Comment by zazoomauro** [comment]
@pinnprophead I would like to understand what's the issue with windows... `-` is a valid character in every single OS.
