### ISSUE TITLE
Autowiring for Pure Javascript

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#124]
Example:

imagine we have something like this in:
services/someClient.js

```js
export default class SomeClient 
{
...
}
```

```yaml
services:
    _defaults:
        autowire: true
```

and then you can start using your `SomeClient` automatically like this:

```js
export default class HelloWorldService
{
    constructor(someClient)
    {
        this._someClient = someClient
    }
}
```

Implementation:

* Strict autowiring for pure Javascript: Filename AND Class name must have the same name. (allow camelcase - underscore naming)
* Autowire will generate a compiled version of container configuration in yaml/js/xml file with the autowire classes. For production environments. Improves performance

**Comment by carere** [comment]
Hello @zazoomauro :) Do you have some hints on how to implement this feature ? Maybe, we could start a discussion about this ?

**Comment by zazoomauro** [comment]
I spent some days working on it and I think this is not the right approach...
May we have to rethink the main idea of autowiring on pure javascript
I'll close this issue
