### ISSUE TITLE
Can`t use NDI in submodule

### ISSUE THREAD

**Issue by HKFiliatix** [zazoomauro/node-dependency-injection#140]
becuase of require(path.join(fromDirectory, classObject)) I can't use NDI inside the submodule. Require.resolve try to load module from every level of path:
```
dir1/dir2/dir3/node_modules/module_name
dir1/dir2/node_modules/module_name
dir1/node_modules/module_name
```
But NDI will try only `dir1/dir2/dir3/node_modules/module_name`.

**Comment by zazoomauro** [comment]
can you please leave an example of usage please?

**Comment by zazoomauro** [comment]
@HKFiliatix can we close this issue?

**Comment by Crusader4Christ** [comment]
I have several npm packages (for ex. app1, app2). Every of them can work as separate application and have own NDI instance and yml configs. Every application have own dependencies.

But now I need to use this packages in some big applications BigApp together:
```
BigApp
  node_modules
      app1
      app2
...
      package
```
So if app1 use some package it will try to find it in folder
`BigApp/node_modules/app1/node_modules/package`
and right folder is
`BigApp/node_modules/package`

#142 is my workaround for this
