### ISSUE TITLE
JsFileLoader not working with module.exports

### ISSUE THREAD

**Issue by harpcio** [zazoomauro/node-dependency-injection#145]
Example:

```
// repositories/UserRepository.js
class UserRepository 
    get model() {
        return User;
    }

    getAll() {
        return this.findAll();
    }
}

module.exports = UserRepository;
```

This is working fine:
```
const di = new ContainerBuilder();
di.register('UserRepository', UserRepository);
```

But this is not working at all:

```
// di/repositories.js
module.exports = {
    services: {
        "repositories.user": {
            class: "../repositories/UserRepository"
        },
    }
};
```

```
const container = new ContainerBuilder();
const loader = new JsFileLoader(container);
loader.load('./repositories.js');
```

Then trying to get this object:
```
container.get('repositories.user');
```

I received this:
```
node_modules/node-dependency-injection/dist/lib/InstanceManager.js:122
      throw new _ServiceNotFoundException["default"](id);
```

The problem is in FileLoader.js, line: 283, I will do PR

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
https://github.com/zazoomauro/node-dependency-injection/pull/146

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
Here you have my repository with full code:
https://bitbucket.org/remotecraftsmen/erp-system/src/master/server/src/di/services.js

Right now is not working because this tiny bug.

**Comment by zazoomauro** [comment]
@rafal-ksiazek-rmtcfm-com thanks!

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
@zazoomauro It's still not working - the change is not updated in npm registry. Maybe you need to update the version of package to 2.6.4?

**Comment by zazoomauro** [comment]
@rafal-ksiazek-rmtcfm-com build is failing! https://travis-ci.org/github/zazoomauro/node-dependency-injection/jobs/695776915

**Comment by zazoomauro** [comment]
Looks like `npm run test:standard`is failing

**Comment by harpcio** [comment]
Sorry for that:
https://github.com/zazoomauro/node-dependency-injection/pull/147

**Comment by harpcio** [comment]
@zazoomauro Can you merge it?

**Comment by zazoomauro** [comment]
Merged
