### ISSUE TITLE
Update fs package reference from NodeJS core instead of npm

### ISSUE THREAD

**Issue by bronskinner** [zazoomauro/node-dependency-injection#154]
I am using this package to configure and resolve services for a nodeJS project. I've noticed that we're getting an odd console message every time we run any code referencing this library. It looks like this package is referencing a version of fs in its package.json. This npm package no longer exists and instead should be installed with nodejs core itself. This doesn't appear to hurt anything but it does mean we get odd console messages when running code that uses this library.

![image](https://user-images.githubusercontent.com/36510746/102661819-96020700-414b-11eb-9a9b-4c4d680c01ef.png)

https://nodejs.dev/learn/the-nodejs-fs-module

**Comment by zazoomauro** [comment]
@bronskinner released

**Comment by zazoomauro** [comment]
Released! https://github.com/zazoomauro/node-dependency-injection/commit/faa74f7f029f901f5e853b1d7b179be292bfb0a8
