### ISSUE TITLE
Each error says: Cannot find module 'XXX'

### ISSUE THREAD

**Issue by daniel-pupczyk-prpl** [zazoomauro/node-dependency-injection#162]
Hi, since I have installed a new version of this package every time any error occurs, error Cannot find module 'XXX' is returned instead. E.g. if I forget to add `async` to function when the inside is `await` then there is an error mentioned above, not a specific one.

**Comment by zazoomauro** [comment]
Can you please paste some code to understand your issue?

**Comment by daniel-pupczyk-prpl** [comment]
as you can se I have added `await` in not `async` function but error said `Cannot find module 'XXX' `
![image](https://user-images.githubusercontent.com/74703045/129517425-bc96e086-7ec7-43b9-ada0-02f8c3b8c282.png)
![image](https://user-images.githubusercontent.com/74703045/129517452-a876f234-5cb2-42e2-882a-8baad3f81c54.png)
