### ISSUE TITLE
Thanks a lot for this awesome package !!!

### ISSUE THREAD

**Issue by carere** [zazoomauro/node-dependency-injection#163]
I just wanted to thank you for this awesome package !!
I switched to TS/JS, and THIS DI component was missing in the JS landscape :D

Do you have a roadmap for this repo ? Do you need help ??

Best regards, and well done ;)

**Comment by zazoomauro** [comment]
check milestones page ;-)

https://github.com/zazoomauro/node-dependency-injection/milestones
