### ISSUE TITLE
When class extends service not found

### ISSUE THREAD

**Issue by slopez93** [zazoomauro/node-dependency-injection#165]
Hi ! First of all thanks for this package, is amazing !

I have this case:

`export class CreateSpaceCommandHandler
  extends CommandHandler<CreateSpaceCommand, CreateSpaceResponse>
{`

In this scenario CommandHandler is an abstract class.

and in the container:

`  Temeria.Spaces.CreateSpaceCommandHandler:
    class: ../../../contexts/Temeria/modules/spaces/application/useCases/createSpace/CreateSpaceCommandHandler
    arguments: ['@Temeria.Spaces.HtmlParser']
    tags:
      - { name: 'commandHandler' }`

When i try to make a call to container always obtain: "Cannot find module '../../../contexts/Temeria/modules/spaces/application/useCases/createSpace/CreateSpaceCommandHandler'"

But if instead of extends use an interface works fine, example:

`export class CreateSpaceCommandHandler
  implements CommandHandler<CreateSpaceCommand, CreateSpaceResponse>
{`

In this scenario CommandHandlerValidator is interface.

**Always obtain this error when class to registered in DI Container use extends.**

Thanks !

**Comment by slopez93** [comment]
In version 2.6.11 works fine ! But in latest version is throwing this error.

**Comment by zazoomauro** [comment]
@slopez93 should be fixed in version 2.7.3
