### ISSUE TITLE
Autowiring for TypeScript

### ISSUE THREAD

**Issue by zazoomauro** [zazoomauro/node-dependency-injection#169]
Example:

imagine we have something like this in:

```typescript
export default class SomeClient 
{
...
}
```

and this is your configuration

```yaml
services:
    _defaults:
        autowire: true
```

and then you can start using your `SomeClient` automatically like this:

```typescript
export default class HelloWorldService
{
    constructor(client: SomeClient)
    {
        this._someClient = someClient
    }
}
```

Even if you are using inversion principle you can also be able to:

```typescript
export default interface ClientInterface
{
...
}
```

```typescript
export default class SomeClient implements ClientInterface
{
...
}
```

```typescript
import SomeClient from 'interfaces/ClientInterface'

export default class HelloWorldService
{
    constructor(client: ClientInterface)
    {
        this._someClient = someClient
    }
}
```

Automatically SomeClient class will be injected in to HelloWorldService.
If there is multiple interface implementation _autowire_ will fail throwing some specific exception.

**Comment by chuano** [comment]
It would be easier to create a configuration generator at development time, since at runtime we have no typing to discover the services and dependencies.

A console command can parse the typescript files and find the dependencies, generating a json/yaml with the discovered services that can be loaded at runtime.

Maybe it could even be a separate project, so as not to burden this one with unnecessary dependencies.

What do you think?

**Comment by zazoomauro** [comment]
@chuano I made an alpha version of this feature.

**Comment by chuano** [comment]
This looks awesome, I've created a simple test and works like a charm. The only problem I see is that this only works using ts-node, if you compile the code and run with node directly it doesn't work, as expected.

Is ts-node ready for production? I have never used it in production and I don't know if its performance and memory usage is the same,.

Do you have some experience with ts-node in production.

Thank you for this, it's awesome!

**Comment by zazoomauro** [comment]
@chuano actually you are right. Right now, Autowire is only available for ts-node or pure node with ts-node/register
