### ISSUE TITLE
findTaggedServiceIds return empty

### ISSUE THREAD

**Issue by DiV666** [zazoomauro/node-dependency-injection#197]
Hi,

I have added a tag in a container.register like this:
```
container
        .register('Scaffolding.User.UserUpdate', UserUpdate)
        .addArgument(new Reference('Shared.BunyanLogger'))
        .addArgument(new Reference('Scaffolding.User.UserMongoRepository'))
        .addArgument(new Reference('Shared.EventBus'))
        .addTag('domainEventSubscriber');
```

But the findTaggedServiceIds method always return an empty iterator:
```
const subscriberDefinitions = container.findTaggedServiceIds('domainEventSubscriber');
console.log(subscriberDefinitions);  // => GeneratorFunctionPrototype [Generator] {}
```

version 3.0.5
I am doing something wrong?

**Comment by zazoomauro** [comment]
@DiV666 Can you try to **compile** the container before executing **findTaggedServiceIds**?

**Comment by DiV666** [comment]
yes, even running compile before, returns an empty iterator

**Comment by zazoomauro** [comment]
Is returning a Generator not an array.
Try to iterate it with a for…
You will find all your services
