### ISSUE TITLE
Autowiring seems only to work with private constructor properties

### ISSUE THREAD

**Issue by abadb** [zazoomauro/node-dependency-injection#203]
Let's assume the following case:

1. Using the container loading a YAML file
2. Autowiring is set to true.

Then, If I have:

1. An interface

```ts
export default interface QueryBus {
    ask<R extends Response>(query: Query): Promise<R>;
}

```

3. An implementation of this interface

```ts

export default class SimpleQueryBus implements QueryBus {
    constructor(private readonly handlers: QueryHandlersRegistry) {

    }
}

```

4. A client which uses this QueryBus interface:
```ts
export default class SampleGetController implements ControllerBase {

    private queryBus: QueryBus;

    constructor(queryBus: QueryBus) {
        this.queryBus = queryBus;
    }
}
```

If using autowiring (loading a YAML file):

```yaml
services:

  _defaults:
    autowire: true
```

The  const typeNameForArgument assignment will fail on the async _getDefinition(classDeclaration, body, parsedFile, ServiceClass) method:

```ts
for (const parameterDeclaration of constructorParams) {
        const typeNameForArgument = parameterDeclaration.parameter.typeAnnotation.typeAnnotation.typeName.name;
        const argumentId = await this._getIdentifierFromImports(typeNameForArgument, body, parsedFile);
        if (!argumentId) {
          continue;
        }
        definition.addArgument(new _Reference.default(argumentId), definition.abstract);
      }
```

When resolving the StatusGetController service, it will throw an exception.

I think this happens because the typescript-eslint parser returns a different data structure when resolving constructors which dont use private properties.

If using private constructor properties:

```ts

interface TestInterface {

}

class ExampleClass {

  constructor(private readonly parameter: TestInterface) {
    
  }

}
```

The parameterDeclaration.parameter.typeAnnotation.typeAnnotation.typeName.name will be present, as resolved by the typescript-eslint parser:

<img width="565" alt="Captura de pantalla 2023-07-17 a las 16 42 00" src="https://github.com/zazoomauro/node-dependency-injection/assets/655278/df19c026-cb2c-4c82-87ce-b8eaf143aeef">

However, if not using private property constructors, like:

```ts

interface TestInterface {

}

class ExampleClass {

  private thing: TestInterface;

  constructor(parameter: TestInterface) {
    this.thing = parameter;
  }

}
```

The parameterDeclaration.parameter.typeAnnotation.typeAnnotation.typeName.name will throw an error, because typescript-eslint resolves this structure to:

<img width="574" alt="Captura de pantalla 2023-07-17 a las 16 46 41" src="https://github.com/zazoomauro/node-dependency-injection/assets/655278/642c7acd-8c9f-42f5-876c-c1c3ea420b10">

And the parameter.typeAnnotation property does not exist when using this declaration.

So, I would suggest to change the documentation to reflect that autowiring only works with private constructor properties.

**Comment by zazoomauro** [comment]
@abadb Thanks! I'll update the documentation in order to reflect your suggestion.
As well I will create a task in order to make it working with protected and public attributes on constructor

**Comment by zazoomauro** [comment]
https://github.com/zazoomauro/node-dependency-injection/wiki/Autowire
