### ISSUE TITLE
Vitest compatibility

### ISSUE THREAD

**Issue by ManuPerezDev** [zazoomauro/node-dependency-injection#209]
We are trying to run our project with node-dependency-injection and Vitest. 

Our tests fails once we need to load yaml files when we start the application to run e2e tests.

<img width="1101" alt="image" src="https://github.com/zazoomauro/node-dependency-injection/assets/44470187/e29d2c99-e65c-410c-ae4c-a64fcfc3aa13">

Any idea of what could be happening?

We are using: 
- TypeScript 5.3.3
- Node Dependency Injection 3.1.2
- Vitest 1.3.1

**Comment by ManuPerezDev** [comment]
We manually registering the services and It works but the yaml loader does not.

**Comment by zazoomauro** [comment]
@ManuPerezDev can you provide the configuration?

**Comment by AlejandroPerez92** [comment]
Do you only encounter the error with Vitest? I have a similar issue in a Nuxt3 project, I have only managed to get it working by registering the services in TypeScript.
