### ISSUE TITLE
Reference Symfony as a source of inspiration

### ISSUE THREAD

**Issue by clement-michelet** [zazoomauro/node-dependency-injection#42]
First of all, good job on implementing DI for JavaScript. Coming from Symfony ecosystem, it's what i've been looking for and will use it for a project. 

But, I'm a little disappointed to not see any reference to the framework as a source of inspiration, especially when most of the architecture comes from it. It's usually a good faith to tell where the inspiration comes from. 

So, my issue/request is just to add a reference to Symfony in the `README.md` file

**Comment by zazoomauro** [comment]
Agree! 90% of the interface comes from Symfony so .... you are totally right
