### ISSUE TITLE
FileLoader cannot load files in subfolder

### ISSUE THREAD

**Issue by clement-michelet** [zazoomauro/node-dependency-injection#50]
Hi,

With `node-dependency-injection` 1.8, when I load multiple files in the same subfolder, the first file is loaded but the second is not loaded and throw an error. The reason is that the previous subfolder is kept in memory and used in the the current import.

A sample project is available at this URL : http://code.runnable.com/WPoVQNvp3IoMwcT4/node-dependency-injection-bug-with-fileloader-subfolder-for-node-js-and-hello-world

**Comment by zazoomauro** [comment]
@clement-michelet Thanks!

**Comment by zazoomauro** [comment]
available on v1.8.2
