### ISSUE TITLE
Allow complex parameter & arguments

### ISSUE THREAD

**Issue by clement-michelet** [zazoomauro/node-dependency-injection#52]
For a service, I need to pass a configuration object as an argument.

My use case is a custom factory using `axios` library which receive a configuration object (base URL, custom headers, etc.) and return a configured instance of axios.

I can neither use parameter or direct arguments to pass my configuration to my factory.

With a parameter configuration like this :
```json
{
  "parameters": {
    "api_client.facebook.config": {
      "baseURL": "https://graph.facebook.com/v2.9"
    }
  }
}
```

The configuration cannot be loaded. There is a type check on parameter value.

When using a service configuration like this :

```json
{
  "services": {
    "api_client.facebook": {
      "factory": {
        "class": "../../../service/factory/axios-factory",
        "method": "create"
      },
      "arguments": [
        {
          "baseURL": "https://graph.facebook.com/v2.9"
        }
      ]
    }
  }
}
```

There is an error because the argument is expected to be a string (for argument replacing).

My change proposal is to :
* simply allow complex types
* or introduce a flag (ex: `~json({"foo": "bar"})`) to pass the parameter to a parameter converter

**Comment by zazoomauro** [comment]
Is exactly the expected behaviour:

`TypeError: The expected value is not a flat string, an array or boolean`

But I agree with you. Let's do it for the 1.10 version

**Comment by clement-michelet** [comment]
The solution and the "planning" are totally fine for me.
