### ISSUE TITLE
Support PackageReference syntax as class in Definition

### ISSUE THREAD

**Issue by cmichelet-wh** [zazoomauro/node-dependency-injection#53]
**Usage:**

For example, I want to declare a redis client from [ioredis](https://www.npmjs.com/package/ioredis) package as a service.

I expect to be able to use the PackageReference syntax (i.e. `"class": "%ioredis"`) to use it instead of having to walk to the class file in `node_modules` folder (i.e. `"class": "/path/to/node_modules/ioredis/lib/index"`).   

Using PackageReference syntax produce an error because the loader try to require the file from the current folder.

**Proposal:**

Update the method `FileLoader._requireClassNameFromPath` to handle PackageReference syntax.

I will work on a PR for this and will push it on 1.9 branch.

**Comment by zazoomauro** [comment]
What about defining it as a simple Reference?

**Comment by clement-michelet** [comment]
I use relative path as a workaround for my project. But I don't like to rely on the relative path to the package. I prefer to rely on require / import package with the package name. It's the publicly exposed way of accessing package content.

Another advantage is to make the reference to the class more portable. You can move the configuration file without having to update the package reference.

**Comment by zazoomauro** [comment]
is exactly what I don't understand. Package reference already exists and
use %ioredis is exactly the same as `import redis from 'ioredis'`
why you need to walk in to the _node_modules_ class file?
