### ISSUE TITLE
Add environment var resolution in run time with especial notation

### ISSUE THREAD

**Issue by alberto-leon-crespo** [zazoomauro/node-dependency-injection#86]
In symfony, you can resolv enviroments variables with `%env(VAR_NAME)%`. I modify FileLoader to replace this sintax with value of the same varible name in `process.env`. I can upload commits with modifications associted to this issue. Can u authorize me to make a pull request?

**Comment by zazoomauro** [comment]
@alberto-leon-crespo any update on this?

**Comment by igordeoliveirasa** [comment]
I really need this feature! How is it going?

**Comment by zazoomauro** [comment]
@alberto-leon-crespo do you have any update on this? I'll reassign it to me

**Comment by barinbritva** [comment]
How can use process.env now in yaml or json configs?

**Comment by barinbritva** [comment]
@zazoomauro, here is my solution for it - https://github.com/zazoomauro/node-dependency-injection/pull/133

**Comment by zazoomauro** [comment]
released to version 2.5.0. Thanks @barinbritva
