### ISSUE TITLE
Register container as a service

### ISSUE THREAD

**Issue by alberto-leon-crespo** [zazoomauro/node-dependency-injection#87]
Im trying to register own container as a independent service. I inject container as a service called "@service_container". I declare a CompilerPass and create in container a circular reference with container. But when i compare injected "@service_container" and parent container objets are diferent.

Any idea how to make this feature?

**Comment by zazoomauro** [comment]
@alberto-leon-crespo https://github.com/zazoomauro/node-dependency-injection/wiki/ContainerBuilderAsReference
