### ISSUE TITLE
Nested compiler passes priority

### ISSUE THREAD

**Issue by Elminday** [zazoomauro/node-dependency-injection#92]
I faced a problem when trying to implement nested compiler passes with priorities.

I want **ServiceCompilerPass** to use nested **UserCompilerPass**. Both of these have to compile BEFORE **FormConfigCompilerPass**.

So I give higher priority to both of these compiler passes, and 0 to **FormConfig** one (lowest).

```
class UsersCompilerPass {
  process(container) {
    console.log('users CP');
  }
}
class FormConfigCompilerPass {
  process(container) {
    console.log('FormConfig CP');
  }
}
class ServicesCompilerPass {
  process(container) {
    console.log('Services CP');
    const instance = new UsersCompilerPass();
    container.addCompilerPass(instance, PassConfig.TYPE_BEFORE_OPTIMIZATION, 1);
  }
}
const container = new ContainerBuilder();
const servicesCP = new ServicesCompilerPass();
const formCP = new FormConfigCompilerPass();
container.addCompilerPass(servicesCP, PassConfig.TYPE_BEFORE_OPTIMIZATION, 2);
container.addCompilerPass(formCP, PassConfig.TYPE_BEFORE_OPTIMIZATION, 0);
container.compile();
```

Result of execution order is:

> FormConfig CP
> Services CP
> users CP
> 

As you can see form config gets executed first.

If I swap up priorities to:

```
FormCfgCP === 2
ServicesCP === 1
UsersCP === 0

```
I get this execution order:

> Services CP
> FormConfig CP
> users CP
> 

What am I missing here @zazoomauro ?

**Comment by Elminday** [comment]
Desired execution order is:

> Services CP
> users CP
> FormConfig CP

**Comment by zazoomauro** [comment]
I’m on holidays at the moment.
I’ll be back on Monday 3th December.

**Comment by zazoomauro** [comment]
@Elminday So, at the moment what you are trying to achieve is not possible.
You are trying to change the priority of compiler pass execution during the container compile and this is impossible. If you want this feature, feel free to do a PR. The key here is change the `CompilerPass` `_getCompilerPassPriorityNumber` method.

**Comment by Elminday** [comment]
Understood, thanks!

**Comment by Elminday** [comment]
@zazoomauro

The thing that I am trying to achieve is:

ServicesCP tag all my services.

After that I want to get all the services tagged and create according number of formConfigs with factories.

Maybe where is a solution you would propose?

I can think of one way:

Services get compiled during TYPE_BEFORE_OPTIMIZATION and FormConfigCompilerPass gets processed during TYPE_OPTIMIZE. (After services are tagged)

**Comment by zazoomauro** [comment]
@Elminday 

I think the best approach is add tags manually in this way:

```yaml
services:
    app.service:
        class: ./someService
        tags:
            - { name: service }
```

and then you can create you form config compiler pass and do whatever you want.
