### ISSUE TITLE
Inline definition settings

### ISSUE THREAD

**Issue by igordeoliveirasa** [zazoomauro/node-dependency-injection#93]
Hi. I'd like to pass definition class parameters inline.. Something like:

```
const dogDefinition = new Definition(Dog, [new Reference("logger")], {shared: false});
container.setDefinition("dog", dogDefinition);
```

Is there any way to do that?

Thanks in advance...

**Comment by zazoomauro** [comment]
I’m on holidays at the moment.
I’ll be back on Monday 3th December.

**Comment by igordeoliveirasa** [comment]
Thanks! I read the docs and learned how to do that. Let's close this one.
