### ISSUE TITLE
Lazy is not working

### ISSUE THREAD

**Issue by igordeoliveirasa** [zazoomauro/node-dependency-injection#94]
Even lazy tests are passing, it's not working.
I guess your lazy tests are not right, since Im not able to get lazy behaviour working.

It's always instantiating...

**Comment by zazoomauro** [comment]
@igordeoliveirasa Can you please give some example?

**Comment by igordeoliveirasa** [comment]
@zazoomauro Is there any channel to chat?

**Comment by zazoomauro** [comment]
@igordeoliveirasa here is fine! just leave here your example and I'm be glad to help you

**Comment by zazoomauro** [comment]
@igordeoliveirasa can i close this issue?
