### ISSUE TITLE
Nested Containers

### ISSUE THREAD

**Issue by igordeoliveirasa** [zazoomauro/node-dependency-injection#97]
Let's suppose I have multiple libraries that besides exporting its classes exports a container. Is there any way to extend those libraries containers in my main app container?

**Comment by zazoomauro** [comment]
@igordeoliveirasa there is no way to merge containers. feel free to PR

**Comment by igordeoliveirasa** [comment]
I really would like to contribute if I were able, but unfortunately I can't these days...

**Comment by zazoomauro** [comment]
Btw... you can do it manually if you want with a custom CompilerPass
