### ISSUE TITLE
Does the library support factory classes?

### ISSUE THREAD

**Issue by igordeoliveirasa** [zazoomauro/node-dependency-injection#98]
I'm not asking about Factory method (like static method inside a class). I'm asking like ShapeFactory example in this link: https://www.tutorialspoint.com/design_pattern/factory_pattern.htm

**Comment by zazoomauro** [comment]
mm... a possible approach could be:

```js
definition.addMethodCall('draw', [new Reference('some_service')]);
```

of course you can do it with yaml or json config file as well.

**Comment by igordeoliveirasa** [comment]
@zazoomauro, Actually I have multiple builders classes that generates some objects. And I have services that requires that objects to be injected. I'd like to inject objects being generated by some builder classes.

**Comment by zazoomauro** [comment]
You can actually use tags and compiler pass to achieve this.
You can check the docs about tagging and compiler pass.

**Comment by igordeoliveirasa** [comment]
Thank you so much!
