### ISSUE TITLE
Passing null argument

### ISSUE THREAD

**Issue by igordeoliveirasa** [zazoomauro/node-dependency-injection#99]
How could I pass null to a constructor argument?

**Comment by igordeoliveirasa** [comment]
When I set like: arguments: [null, "argB", "argC"] I received the following error message: 

```
_iteratorError: TypeError: Cannot read property 'slice' of null
```

**Comment by zazoomauro** [comment]
@igordeoliveirasa is not possible at the moment. is a bit strange to send a null service...

**Comment by igordeoliveirasa** [comment]
Actually it's not a null service, it's a constructor argument required by a service that may be null..

**Comment by igordeoliveirasa** [comment]
That's why I'd like to have a chat channel, lol. I have multiple things to argue about.

**Comment by zazoomauro** [comment]
@igordeoliveirasa usually nullable parameters are always at the end of the arguments list like:

```js
class SomeClass {
  constructor(service1, service2, nullableService = null) {}
}
```

**Comment by igordeoliveirasa** [comment]
Wow! That's an awesome tip. Thank you so much.
